# https://github.com/al-one/hass-xiaomi-miot/blob/master/.github/workflows/release.yaml
name: Release

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  release-zip:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: ZIP Component Dir
        run: |
          cd ${{ github.workspace }}/custom_components/qingping_iot_cloud
          zip -r qingping_iot_cloud.zip ./

      - name: Upload zip to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ github.workspace }}/custom_components/qingping_iot_cloud/qingping_iot_cloud.zip
          asset_name: qingping_iot_cloud.zip
          tag: ${{ github.ref }}
          overwrite: true